### ISSUE TITLE
Resolve ip dependency warnings

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#100]
Please resolve dependebot and security warnings for the following projects: 

- [x] Leaderboard
- [x] abortion.ca.gov
- [x] design-system

**Comment by xjensen** [comment]
Leaderboard is **done** (already handled via other recent work).

Abortion.ca.gov is **done** (via cagov/abortion.ca.gov#204).

Design System is **done** (via cagov/design-system#1014).
