### ISSUE TITLE
 Sunset covid19.ca.gov

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#105]
- [x]  Remove all AWS resources
- [x]  Change Pantheon from Basic to sandbox
- [x]  Update GitHub read mes
- [x]  Change GitHub repos to public archive
- [x]  Archive all covid Slack channels
- [x]  Remove alerts in Google Cloud Platform and Better Uptime
- [x]  Turn off Github automated actions (probably covered by archiving repos).
- [x]  Turn off monitoring daemons.
- [x] Clean up Engineering wiki
- [x] Turn off the email Peggy gets for it from Google Console.
- [x] Turn off the Page Feedback email Peggy gets from it (SurveyMonkey)
- [x] Unpublish teamdocs.covid19.ca.gov 
- [x]  Change status to "Done" in capacity tracker
- [x] Remove unused subdomains (files. static. staging. pr. teamdocs. from DNS config).
- [x] Unpublish handbook.digital.ca.gov
- [x] Remove handbook.digital.ca.gov domain
- [x] Remove Cloudwatch alert
- [x] Notify procurement and IT, that we are using 1 less Pantheon instance

_This is a duplicate of https://github.com/cagov/covid19/issues/7805 which can't be edited because parent repo is archived._

**Comment by zakiya** [comment]
Removed GCP,  Better Uptime, and AWS CloudWatch alerts.

**Comment by jbum** [comment]
Chach is the Pantheon site owner.  I can't change Covid-19 site status.  
I've archived the one Slack channel I created, but will need help with the others. Opening a ticket.

**Comment by jbum** [comment]
The page feedback processing is handled by the data team.  In theory, Peggy shouldn't get any more page feedback email since the form no longer exists, but the data team likely needs to tear down some stuff.  I'll notify Britt.

**Comment by jbum** [comment]
Britt told me to talk to Shaheen re: feedback/surveymonkey.  Don't currently see any Covid-specific tables in DynamoDB, the database used to collect feedback, although there are two "Innovation" tables (used for the innovation website feedback).

**Comment by zakiya** [comment]
Downgraded Pantheon and marked project as done in the Capacity tracker.

**Comment by zakiya** [comment]
- Covid Slack channel archived. 
- Told Peggy I'd help her unsubscribe from Survey Monkey
- CDT manages subdomains. Sent a message to Brian Moss on 6/12 informing him since I no longer have manager access to that domain. 
- Sent a message through ServiceNow to remove handbook.digital.ca.gov

Closing issue

(🎉  and 😭)
