### ISSUE TITLE
AWS infrastructure tracking

### ISSUE THREAD

**Issue by aaronhans** [cagov/odi-engineering#16]
Figure out where we are tracking existing/new AWS infrastructure we are firing up

We want to preserve engineering ability to flexibly spin up new stuff but we don't want to lose track of anything

- Agree on central spreadsheet for tracking infrastructure
- Test and document audit procedures so we know how to retrieve the list of everything in all regions regularly

**Comment by chachasikes** [comment]
Chad & I are going to sync on this week after next.

**Comment by xjensen** [comment]
@aaronhans @chachasikes @ChadABratton Checking in to see if there's anything left to do re: tracking AWS usage.

**Comment by aaronhans** [comment]
We do need assistance from Chad's team here. Right now the engineering AWS accounts can fire up infrastructure at will but we can't view the billing dashboards. 

We need elevated permissions so we can audit our current usage costs by service manually and setup alerts for cost thresholds.

**Comment by ChadABratton** [comment]
CDT is going to give us access to a new AWS billing panel. I will let everyone know as soon as this is ready. It should be this month.

**Comment by zakiya** [comment]
I have access to the Rackspace billing dashboard for AWS now.
