### ISSUE TITLE
AWS expense collars

### ISSUE THREAD

**Issue by aaronhans** [cagov/odi-engineering#17]
We are using AWS effectively for high traffic applications but our planned expenses should be very low.

We can apply low expense thresholds that will catch unexpected runaway systems that are incurring unplanned cost.

**Comment by xjensen** [comment]
@aaronhans @ChadABratton Checking in to see if we've done any work on implementing service quotas on AWS.

**Comment by aaronhans** [comment]
not yet

**Comment by zakiya** [comment]
AWS has a [Cost Anomaly Detection](https://us-east-1.console.aws.amazon.com/cost-management/home?region=us-east-1#/anomaly-detection/overview) service. Will discuss at the next IT/Engineering meeting.

**Comment by zakiya** [comment]
Moved to IT's task list.
