### ISSUE TITLE
QnA crawler readme updates

### ISSUE THREAD

**Issue by aaronhans** [cagov/odi-engineering#2]
We discovered some missing information in the readme in the https://github.com/cagov/qna-crawler repository.

Missing a description of the following required steps in the qnamaker section:

- Log into qnamaker.ai
- You should see the call center as one of the knowledge bases once logge din
- Check with teammates if you have permission problems and don't see the call center knowledge base. If you have multiple azure account profiles associated with the same account try both
- Accounts need contributor access to the QA-GO-COVID-001 resource in Azure in order to modify the knowledge bases
- Click on the call center knowledge base
- record the number of QnA pairs listed at the top
- Click on settings in the top nav
- In the import knowledge base section click the import button
- Choose the xlsx file you just generated by running the scripts above
- The import should complete and take you back to the knowledge base edit screen
- Review the number of QnA pairs now, did it change as expected?
- Review the format of questions. All of them (except for Larry David's which has some HTML) are formatted with markdown and should show a preview mode in the edit screen that preserves line breaks
- If the questions look alright here click publish in the top nav
- This will update the endpoints serving the production site and the latest QnA content will be live

Would help to have screenshots of steps like what markdown answers look like in the edit screen when everything is fine

**Comment by chachasikes** [comment]
Slack thread with our full system review & more notes.

Next steps:
- Revise README in cagov/qna-crawler with notes and missing steps.

**Comment by chachasikes** [comment]
@jbum OK to close?

**Comment by xjensen** [comment]
Closing for now. Can reopen as needed.
