### ISSUE TITLE
dynamic previews with 11ty

### ISSUE THREAD

**Issue by aaronhans** [cagov/odi-engineering#22]
Thanks for looking into using Eleventy serverless https://www.11ty.dev/docs/plugins/serverless/ to do dynamic previews from our CMS

Getting the WordPress preview link to point to this service will be a separate task tracked in a different ticket

**Comment by carterm** [comment]
The preview mode feature is fully functional now.
https://github.com/cagov/11ty-serverless-preview-mode

Ready to start looking at integrating it with drought.
