### ISSUE TITLE
Come up with a name for our testing/development headless pipeline

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#24]
We need a development/testing pipeline. 

Purpose:
* Work out publishing system integration tasks & features without impacting production sites
* Have a reference of the default installations for our services.
* Cross-train engineers on setting up different systems & independently review our services (trying technical documentation & raising issues)

Publishing pipeline components:

1. CMS: Currently WordPress, have plans to use others
    Repo: @cagov/odi-publishing-pantheon (installer)
       Children: 
      -  @cagov/ca-design-system-gutenberg-blocks
      - ... (there are more, will fill in) 
      - Editor instance:
        dev - wipeable sandbox instance - and development versions of plugins and features
        live - production - has our sample content & `main` released versions
        - dev version needed for building preview feature without negatively impacting production sites
2. Data models (Need to work on this)
3. Design system components (repo is @cagov/design-system, `main` branch is the source)
4. Microservices - endpoints on FaaS (currently Azure, could be Lambda) to sync API data to github
5. 11ty build (we need this, also preview feature needs this) - projects needs a reference - reference can be the `main` branch - and new features in `development` branch which can deploy to appropriate s3 buckets
6. s3 buckets
7. optional - CloudFront configs & custom domains. Chad & Chach will go over service documentation & tracking requirements.

Docs: live in wiki in ___ (which repo? currently odi-engineering -- -does odi-publishing need a repo)

Note: odi-publishing is our working name so we can sync up our work.

**Comment by chachasikes** [comment]
@zakiya  and @xjensen  tagging you - next week we can try to work on #4 here.

**Comment by m-sullivan7** [comment]
Quick check: I got alerted via email to the creation of this issue. Is there anything you need from me here? (Didn't see my name anywhere in it. 😉)

**Comment by britt-allen** [comment]
Same Q as Michael. If I am not needed, how can I be removed as it seems I
might be part of an auto listserv?

**Comment by abquirarte** [comment]
You can change your settings under "watch" :)

[image: Screen Shot 2021-10-05 at 5.10.05 PM.png]

Angelica Quirarte, "Angie"
Deputy Director | Office of Digital Innovation
c: 916-526-5510 or 916-812-6864
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by chachasikes** [comment]
Done!
