### ISSUE TITLE
Set up a full microservice endpoint for one of our publishing projects

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#25]
See [#24](https://github.com/cagov/odi-engineering/issues/24)

4 - Microservices.

- [ ] Organize random notes on service configuration - IN PROGRESS/Cross-training
- [X] Locate a board to track issues when reviewing the service

**Comment by chachasikes** [comment]
All the pantheon instances are complete.

**Comment by zakiya** [comment]
I'm going close this since it is in the **Done** column.

**Comment by zakiya** [comment]
I just noticed this issue is also on two other boards. Going to assign to @chachasikes for clarification/next steps.
