### ISSUE TITLE
Unit Testing for components

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#28]
- when are visual regression tests appropriate
- how do we regression test changes to components before they are delivered to other projects
- cypress, playwright
- linting
- accessibility
- storybook, lit for preview?

**Comment by chachasikes** [comment]
@zakiya Safe to close this for now? Do you want to write any follow ups & let this get prioritized in scoped work?

**Comment by zakiya** [comment]
Going to close. We have most of these things now and others will come up elsewhere.
