### ISSUE TITLE
ODI publishing testing pipeline

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#46]
Create a generic sandbox pipeline to test odi-publishing.

- [ ] Priority 1: When editor pushes "Publish" __(editor url)__ content writes __correct_content to __correct github repo/branch__ and it updates on __correct s3 bucket__  [future: then sends correct response to correct notification/response service.] - Type: Trigger event.

Reference: test priorities:
1. polling
2. **trigger notifications** - using this to develop tests
3. staging
4. preview rendering

TBD:
- Testing menus 
- Testing redirect

**Comment by zakiya** [comment]
Repo for testing here: https://github.com/cagov/odi-publishing-test/

**Comment by chachasikes** [comment]
Works locally - 
another step for another person to run it.

**Comment by chachasikes** [comment]
This week - make the development pipeline.

Then use the tester.

**Comment by chachasikes** [comment]
This might be a duplicate

**Comment by chachasikes** [comment]
Updated all the pantheon instances & made mirrors repos.
Linked on Github board for Editor / CMS

**Comment by zakiya** [comment]
@chachasikes Which pantheon instances were updated?

**Comment by chachasikes** [comment]
Closing this one. If we regroup on this it will need to be part of a managed sprint.
