### ISSUE TITLE
use git actions cache to speed up builds

### ISSUE THREAD

**Issue by aaronhans** [cagov/odi-engineering#48]
We deal with heavy dependencies in our builds because we need headless browsers to run e2e tests against open PRs before we approve them for merging.

Thanks to @zakiya and @xjensen for leading us toward this promising solution: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows

This looks like a great way to speed up recurring builds which will most likely use the same version of the heavy dependencies

**Comment by xjensen** [comment]
Currently evaluating a solution in cagov/drought.ca.gov#304.

We'll see how it goes, then do it on the other sites if all looks good.

**Comment by zakiya** [comment]
This is live on drought.

**Comment by zakiya** [comment]
Going to close this. We can use the drought as an example for the future.
