### ISSUE TITLE
Keep improving merge bash script

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#49]
We are working on a shell/bash script that helps with safe merging between development/main branches.

We will also need this for handling changes with staging/preview branches.

Creating a ticket to keep this going, it's more an infrastructure feature than project work.

https://github.com/cagov/drought.ca.gov/issues/167

**Comment by xjensen** [comment]
I'm going to close this one. 

Since we opened this Issue, it's been my experience that one script rarely fits all scenarios. Yet, our current scripts are a great starting point for most tasks. I recommend we keep this practice going, without the goal of creating one script to rule them all.
