### ISSUE TITLE
Complete diagram of ODI Publishing

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#52]
Zakiya started a diagram of the ODI Publishing system and shared it with Jon & Chach.

We used Figma's FigJam to edit the technical diagram.

We would like more feedback from non-engineers on the diagram so that our diagram is accurate to how the system is built, and useful for all our team members and partners who might want to understand how our system is configured.

Note: @aaronhans also created a great system architecture diagram of the hardware system (It's in @cagov/drought.ca.gov.)

**Comment by chachasikes** [comment]
Pausing this til we catch up. 
A good outcome for this would be a couple of slides to be able to use in presentations.

**Comment by chachasikes** [comment]
Updates: 
* We revised the diagrams last week.
* Jared is going to work on a more general version of the diagram.
* We started using post-its in FigmaJam to indicate where in the pipeline we need more robustness/configuration clarity.
* Pair diagramming is helpful when a system needs documentation. (Could be FigmaJam or LucidCharts)

**Comment by jaredwyee** [comment]
First draft of super abstracted diagram https://docs.google.com/presentation/d/1rhY8S-4XW9V6OHDM0u5aGqsn5K3KGnsZ0HS1iAcXfhc/edit#slide=id.p

**Comment by chachasikes** [comment]
This really has evolved! It's a stellar dynamic system diagram now. Go us. :)
