### ISSUE TITLE
Per-PR Preview Sites in AWS

### ISSUE THREAD

**Issue by xjensen** [cagov/odi-engineering#53]
For our sites on AWS, let's set up automatic preview sites per branch, triggered upon PR. This would be similar to what Azure tried (but often failed) to do for PRs in Covid.

Here's the general outline.

1. Request a new DNS entry, such as `pr.drought.ca.gov` or `demo.drought.ca.gov`.
2. Point it to a **single** Cloudfront distribution.
3. Create a **single** S3 bucket.
4. Create a GitHub Action for non-`main` branches. This GH Action will push the 11ty build into a **subfolder** of the S3 bucket. There would be a folder in the S3 bucket for each branch.
5. Create a Lambda@Edge function in Cloudfront that serves subdomain requests from the corresponding S3 subfolder. `fix-my-bug.pr.drought.ca.gov` would pull files from the `fix-my-bug` folder in the S3 bucket. (This would be a "Viewer Request" function in Cloudfront's language/interface.)
6. Set up an S3 policy to expire/delete files in this bucket after a period of time. (60 days?)

This plan makes efficient use of resources. We avoid creating tons of Cloudfront distributions and S3 buckets, which is both messy and expensive. Instead, we use one cheap Lambda function.

Open to suggestion if there are better ideas in part or in full.

**Comment by chachasikes** [comment]
@aaronhans  Is this for the backlog? (Found it in issue clean up this AM)

**Comment by aaronhans** [comment]
Thanks for finding this! 

This is important because it gives us the modern experience of immediately browseable, cloud hosted, production architecture based version of the site based on every open PR without any limits (Like we run into on Azure Static Web Apps)

I gave it a p2 since it isn't blocking any of our high priority goals. It should stay in backlog on the static site gen board and I assigned it to jon

**Comment by aaronhans** [comment]
Glad @xjensen mentioned this issue in the robots disallow crawling discussion. It will be important to make sure that all of these development instances get the appropriate disallow directives when they are being spun up.

**Comment by xjensen** [comment]
We now have a nearly working example of this in Drought via cagov/drought.ca.gov#211. (Just need to merge cagov/drought.ca.gov#213 to apply a few clean-up fixes to the GitHub Action after observing it in action.)

Leaving this open, for now, pending the following concerns.

* Need to decide if/when we want to apply this technique to other sites.
* Need to complete documentation.
* Bonus points for capturing this as a CloudFormation template for automated deployments on new sites.

**Comment by aaronhans** [comment]
So cool to see this coming together. Really happy you found the time to get this setup and got the git workflow code in review already!

We want this on all sites ASAP and have reviewed one PR for it already, so should move back into todo when the open PRs are merged

**Comment by aaronhans** [comment]
Great work on this @xjensen! 

This ticket is ready to close now right?

I opened up these follow up tickets to implement this on cannabis and covid19:
https://github.com/cagov/cannabis.ca.gov/issues/437
https://github.com/cagov/covid19/issues/5692

**Comment by xjensen** [comment]
Cool, thanks for opening those other tickets! 

I'd like to keep this open until the documentation is finished, hopefully by end of day. Stay tuned.

**Comment by xjensen** [comment]
[Documentation](https://github.com/cagov/odi-engineering/wiki/Set-up-PR-preview-sites) now available. 

I'll go ahead and close this ticket; feel free to reopen if anything else is needed.
