### ISSUE TITLE
Propagate production install flag to all repos

### ISSUE THREAD

**Issue by aaronhans** [cagov/odi-engineering#54]

**Comment by xjensen** [comment]
@aaronhans Was this issue about replacing `npm install` with `npm ci --production` in all of our GitHub Action deployment scripts?

**Comment by aaronhans** [comment]
yes, thanks for implementing this in some places already @xjensen

**Comment by zakiya** [comment]
@xjensen @aaronhans Can you list out where this is implemented and were it isn't?

**Comment by xjensen** [comment]
We have it on Drought already. I believe we still want it on Digital and Cannabis. 

Here's some background for posterity. The purpose of `npm ci --production` is to prevent installation of `devDependencies` during production builds. This can significantly speed up publication time and prevent some errors. The challenge is rearranging the `dependencies`/`devDependencies` in package.json to ensure everything works as expected in all environments.

**Comment by zakiya** [comment]
Note to self: Create individual issues in the cannabis and innovation repos once they've been cleaned up a bit

**Comment by zakiya** [comment]
Going to close this. We can do this with future projects as needed.
