### ISSUE TITLE
design system adaptation on CAWeb theme

### ISSUE THREAD

**Issue by kkoryaka** [cagov/odi-engineering#59]
##  Our goal is to modify CAWeb theme that would be:
- running on design system css from combined-css component 
- no divi or State template styles
- using design system JavaScript from same combined-css component (no jQuery or bootstrap)
- Header and page section are using design system structure 

## WHY: 
- Making CAWeb theme look like design system will give editors consistent visual experience. (Sites will look the same in WP environment as they will look live)
- We could leverage theme's CAWeb options where editors and administrators could control many aspects of the website, such as main navigation, footer navigation, statewide header and footer links, custom css and JS, logo, theme color, search settings, etc.

## Progress:
Contacted with Danny from CAWeb Publishing, he suggested using The "core" branch in CAWeb theme repo as starting. Point. I was able to do initial PR here:  https://github.com/CA-CODE-Works/CAWeb/pull/676

In that PR i did following modifications to the core branch of the CAWeb theme:
### UPDATE STYLES:
/assets/css/cagov/version5.5/colorscheme/
update styles from design system combined-css component
- delta.css replace with drought.css
- eureka.css replace with cannabis.css
- oceanside.css replace with cagov.css
1. In each file remove @supports properties otherwise it will be gulp errors.
2. Move fonts parts of delta.css, eureka.css, and oceanside.css files into cagov.font-only.css file and make sure paths are starts with ../
3. Move all Public-sans fonts into /fonts/ folder as well as CAGov.woff2
4. In gulpfile.js find "sync function buildFrontEndStyles" function
comment out these lines:
// f = f.concat(config.frontendCSS); // f = f.concat( config.SCSSAssetDir + 'cagov/version' + ver + '/custom.scss' );
5. Run gulp frontend-css to generate updated cagov-v5.5-oceanside.css file (note only delta, eureka and oceanside themes will have ds colors)

### DISABLE JQUERY
In functions.php add this code
/** * Completely Remove jQuery From WordPress Admin Dashboard */
add_action('wp_enqueue_scripts', 'no_more_jquery');
function no_more_jquery(){
wp_deregister_script('jquery');
}

### ADD JAVASCRIPT:
Get index.js file from design system's combined-css component and replace /assets/js/cagov/version5.5/cagov.core.js
Remove code from /assets/js/cagov/version5.5/custom.js
Remove this "config.a11yJS" peice of code from async function buildCAWebJS in gulpfile.js
Remove all jQuery code from /assets/js/caweb/google.js
Run gulp cawed-js to generate updated cawed-v5.5.js file.

### Update layout and structure
Update header.php structure to go inline with design system.
Update utility header structure to reflect design system (remove utility icons section and settings button)
Add d-none class to the settings.php section
Update branding.php to reflect design system branding component (remove mobile-controls.php from header) and add similar section to the branding. Add php package lines from search-form.php and mobile-controls.php
Update search form structure
Update navigation inside of header.php
Update navigation structure class-cawed-nav-menu.php inside of /inc folder
Need to work on:
Navigation sub navigation is not set up yet.
JavaScript (not opening nav menu in mobile)
When footer menu is activated it's breaking the page (need to finish up with footer layout)

### Screenshot
![Screen Shot 2021-11-04 at 4 32 51 PM](https://user-images.githubusercontent.com/31669748/140827106-dcbdfc5a-a836-4758-812b-d49853a5a6b0.png)

**Comment by chachasikes** [comment]
Closing this one while cleaning up some boards now that we are starting to get the rest of this backlog cleared.
