### ISSUE TITLE
Create outline of publishing system documentation

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#68]
- [X] Agree on main areas of what we are working on (as-is)
- [ ] Aggregate previous attempts to create a 1-pager about the system
- [X] Set up project board tracking the different threads of the publishing system
- [X] Create a git repo to house wiki content & content model documentation (needed to refer to it in code @DOCS references)

- [ ] Outline main headless publishing system configuration
   - [X] Set up editor service- 0.0.1 (odi-engineering wiki)
   - [ ] Set up github repos with static site generation tool (11ty)
     - [X] Write description of how to set this up
     - [ ] Revise documentation
     - [ ] Improve dynamic diagram docs
   - [X] Set up wordpress-to-github - in progress, through tests (odi-publishing-tests)
   - [X] Set up AWS s3 buckets for production and development workflows - 0.0.1 (odi-engineering wiki)
   - [X] Set up domains - 0.0.1  (odi-engineering wiki)
   - [X] Set up Cloudfront  - 0.0.1  (odi-engineering wiki)
   - [ ] Help content team get started - 0.1.0 - in progress
   - [ ] System status service (test-driven)  - in progress (odi-publishing-tests)
 - [ ] Describe essential system services as tests - in progress (odi-publishing-tests)

**Comment by chachasikes** [comment]
Leaving open as a reminder - because this probably needs a tune up.

**Comment by zakiya** [comment]
I'm going to close this one. If we pick up headless publishing as an entire project again we can revisit.
