### ISSUE TITLE
Check out SMART goals

### ISSUE THREAD

**Issue by chachasikes** [cagov/odi-engineering#7]
@rsanjabi shared the Insight teams SMART goals activity example

I duplicated the Google Sheet framework in case we would like to do it. [Template](https://docs.google.com/spreadsheets/d/1AfEJ-iQOsXV1dm_6BzWL75Oel7mxbgP1XCi_M-Oe9yQ/edit#gid=0)

- [ ] We need the process framework & introduction on how to work through it.
- [ ] Decide as team if we want to try it and support each other, if not - if anyone wants to do it and doesn't have an accountability partner, find someone from elsewhere at ODI.

**Comment by aaronhans** [comment]
It was great that @rsanjabi shared this process and her experience with it with us.

We are missing this type of goal setting where we identify our individual professional needs and figure out how those can be met as part of our work for the state. I think we should try this out

**Comment by chachasikes** [comment]
Adding this to Codeshare "Topics"
