### ISSUE TITLE
Generate WEBP images automatically

### ISSUE THREAD

**Issue by xjensen** [cagov/odi-engineering#76]
Using WEBP image format will help us achieve better performance on our sites. We should look into ways of automatically converting PNG and JPEG formats within our infrastructure or static site builds.

**Comment by zakiya** [comment]
@xjensen Please upload what you have to the 11ty build repo

**Comment by xjensen** [comment]
I've entered a draft PR into 11ty-build-system at cagov/11ty-build-system#3.

**Comment by zakiya** [comment]
Thank you. Moving this to "On hold" since we have a lot of higher priority things going on right now.

**Comment by zakiya** [comment]
Closing because no ticket should be open for a year.
