### ISSUE TITLE
Document Slack channels with automatic notifications

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#80]
Let's document 
- name of channel
- Channel ID
- Type of notices
- What service triggers a notification 
- Link to triggering code if applicable
- Anything else that may be relevant to others

https://cadotgov.slack.com/archives/CVCSH3CR5

Partial list:

#covid19-alerts
#odi-engineering-issues
#testingbot
#twitterfeed
#wordpress-sync-http-trigger

I've started a [table in Coda](https://coda.io/d/_dL_3_CR2bVn/General-info_suDRT#_luVpy) that you can build on

**Comment by jbum** [comment]
Document: https://docs.google.com/spreadsheets/d/1NPlE1zlPfrrw78h0pl1C9MQcHu1nO6L6BE9ZE0zFq04/edit#gid=0

**Comment by zakiya** [comment]
Perfect. Closing.

**Comment by zakiya** [comment]
So very done.
