### ISSUE TITLE
Design system component - D3 charts

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#83]
I'm keeping this out of the design system issue queue for now so it doesn't get lost. 

@jbum and @chachasikes both had ideas about creating one or a series of demo charts for the design system. I think we need to spend some time scoping out exactly what that would look like.

**Comment by chachasikes** [comment]
https://github.com/cagov/odi-engineering/issues/84 Trying to figure out where we could put this code.

* Prototyping in a real project first
* Move to ODI contrib
* Register it on the component feature list that Yesenia (DS PM) would manage
* Propose it and bring it through the component review workflows that Christina is working on.

**Comment by zakiya** [comment]
Closing. Will not do
