### ISSUE TITLE
New! State website alerts during emergencies

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#97]
From Jonathan Porat, Chief Technology Officer

> Good afternoon AIOs and CIOs:
>
> As we prepare for the next emergency response, the State is implementing a new tool developed by the California Department of Technology (CDT) and GovOps Agency to communicate vital emergency information to the public on state websites.  
>
> Unlike past years -- when we’ve needed help from you and your web teams to place emergency messaging for Californians on your sites -- this new tool is automated. Once your Agency and departments opt-in (working with CDT to add code to your site), the emergency messaging – when approved and authorized by the JIC and GO -- will appear automatically on your website to help communicate critical information to the public, and it will come down when no longer needed.
>
> To see how these “State Department Website Emergency Alerts” will look and find instructions on how to participate in this critical system, check out the third item on the attached. Please contact CDT’s Technology Innovation Services Manager Surendra Chenneerappa ([S.Chenneerappa@state.ca.gov](mailto:S.Chenneerappa@state.ca.gov)) to answer any technical questions, and CC me ([Jonathan.Porat@state.ca.gov](mailto:Jonathan.Porat@state.ca.gov)). I am available to answer any questions and concerns.
>
> Thank you for your support for this new effort to ensure uniform, timely messaging across state websites during emergencies.

**Attachments:**
- [GovOps Emergency Communication Tools incl State Website banners - 7 26 23.docx](https://github.com/cagov/odi-engineering/files/12293527/GovOps.Emergency.Communication.Tools.incl.State.Website.banners.-.7.26.23.docx)
- [Technical-doc-State-Deparment-Website-Emergency-Alerts.pdf](https://github.com/cagov/odi-engineering/files/12293528/Technical-doc-State-Deparment-Website-Emergency-Alerts.pdf)
- [web-alerts-presentation-march-2023.pptx](https://github.com/cagov/odi-engineering/files/12293530/web-alerts-presentation-march-2023.pptx)

**Comment by jbum** [comment]
Pull requests created for 

[abortion.ca.gov](https://github.com/cagov/abortion.ca.gov/pull/189) (needs review)
[drought.ca.gov](https://github.com/cagov/drought.ca.gov/pull/316): (merged)
[cannabis.ca.gov](https://github.com/cagov/cannabis.ca.gov/pull/3387) (merged)
[covid19.ca.gov](https://github.com/cagov/covid19/pull/7604) (merged)
[innovation.ca.gov](https://github.com/cagov/innovation.ca.gov/pull/219) (merged)
