### ISSUE TITLE
Remove drought AWS resources and recreate redirect as a Lambda function

### ISSUE THREAD

**Issue by zakiya** [cagov/odi-engineering#98]

**Comment by zakiya** [comment]
Summary of Slack convos with @jbum  @zakiya and @xjensen 

11/20/2023 -  AWS Cloudfront function implemented to redirect all [drought.ca.gov](http://drought.ca.gov/) requests to [cww.water.ca.gov](http://cww.water.ca.gov/).  Cloudfront distribution (and I think the S3 origin) intact for the function to work as intended. 

12/21/2023 - ZK spoke to Katie at DWR. They need to talk to IT about taking on the redirect

So let's redo the redirect as a single Lambda function so we can decommission the S3/Cloudfront infrastructure

**Comment by xjensen** [comment]
I've reimplemented the redirect as a Lambda function. We still need to keep Drought's Cloudfront distribution (because it's a nice way to handle the SSL cert). But everything else can go. I will start dismantling the rest next.

**Comment by xjensen** [comment]
All done.
